name: CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run:  |
            python -m pip install --upgrade pip 
            if [ -f requirements.txt ]; then
              pip install -r requirements.txt 
            fi

    - name: Check types with mypy
      run: |
        if [ -d src ]; then 
          mypy src --ignore-missing-imports
        fi

    - name: Test with unittest
      run: |
        if [ -d tests ]; then 
          pytest tests
        fi

    - name: Lint with Black
      run: |
        black src --check --diff -l 120
        black tests --check --diff -l 120
